name        : jml-java-4          # name of the package
version     : 1.4-1               # version of the package
kind        : spec                # one of tool or spec(s)
description : JML Specifications for the Java Language, Version 4.

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com


